In [2]:
import numpy as np 
import pandas as pd
import datetime

In [4]:
customers = pd.read_csv("D:\AnalytixLabs\Case Studies\Machine Learning Assignments\Customer_360_Analytics_file_creation_assignment_2 - 1740904578730 - 1769931356551\CUSTOMERS.csv")

In [21]:
customers.head()

,customer_id,customer_zip_code_prefix,customer_city,customer_state
0,06b8999e2fba1a1fbc88172c00ba8bc7,14409,Adilabad,Andhra Pradesh
1,18955e83d337fd6b2def6b18a428ac77,9790,Adoni,Andhra Pradesh
2,4e7b3e00288586ebd08712fdd0374a03,1151,Akkarampalle,Andhra Pradesh
3,b2b6027bc5c5109e529d4dc6358b12c3,8775,Akkayapalle,Andhra Pradesh
4,4f2d8ab171c80ec8364f7c12e35b23ad,13056,Alwal,Andhra Pradesh

In [5]:
geo = pd.read_csv("D:\AnalytixLabs\Case Studies\Machine Learning Assignments\Customer_360_Analytics_file_creation_assignment_2 - 1740904578730 - 1769931356551\GEO_LOCATION.csv")

In [20]:
geo.head()

,geolocation_zip_code_prefix,geolocation_lat,geolocation_lng,geolocation_city,geolocation_state
0,1037,-23.545621,-46.639292,Akkarampalle,Andhra Pradesh
1,1046,-23.546081,-46.644820,Akkarampalle,Andhra Pradesh
2,1041,-23.544392,-46.639499,Akkarampalle,Andhra Pradesh
3,1035,-23.541578,-46.641607,Akkarampalle,Andhra Pradesh
4,1012,-23.547762,-46.635361,Akkarampalle,Andhra Pradesh

In [7]:
items = pd.read_csv("D:\AnalytixLabs\Case Studies\Machine Learning Assignments\Customer_360_Analytics_file_creation_assignment_2 - 1740904578730 - 1769931356551\ORDER_ITEMS.csv")

In [8]:
items.head()

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,9/19/2017 9:45,58.90,13.29
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,05-03-2017 11:05,239.90,19.93
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,1/18/2018 14:48,199.00,17.87
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,8/15/2018 10:10,12.99,12.79
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2/13/2017 13:57,199.90,18.14

In [9]:
payments = pd.read_csv("D:\AnalytixLabs\Case Studies\Machine Learning Assignments\Customer_360_Analytics_file_creation_assignment_2 - 1740904578730 - 1769931356551\ORDER_PAYMENTS.csv")

In [10]:
payments.head()

,order_id,payment_sequential,payment_type,payment_installments,payment_value
0,b81ef226f3fe1789b1e8b2acac839d17,1,credit_card,8,99.33
1,a9810da82917af2d9aefd1278f1dcfa0,1,credit_card,1,24.39
2,25e8ea4e93396b6fa0d3dd708e76c1bd,1,credit_card,1,65.71
3,ba78997921bbcdc1373bb41e913ab953,1,credit_card,8,107.78
4,42fdf880ba16b47b59251dd489d4441a,1,credit_card,2,128.45

In [11]:
ratings = pd.read_csv("D:\AnalytixLabs\Case Studies\Machine Learning Assignments\Customer_360_Analytics_file_creation_assignment_2 - 1740904578730 - 1769931356551\ORDER_REVIEW_RATINGS.csv")

In [12]:
ratings.head()

,review_id,order_id,review_score,review_creation_date,review_answer_timestamp
0,7bc2406110b926393aa56f80a40eba40,73fc7af87114b39712e6da79b0a377eb,4,1/18/2018 0:00,1/18/2018 21:46
1,80e641a11e56f04c1ad469d5645fdfde,a548910a1c6147796b98fdf73dbeba33,5,3/10/2018 0:00,3/11/2018 3:05
2,228ce5500dc1d8e020d8d1322874b6f0,f9e4b658b201a9f2ecdecbb34bed034b,5,2/17/2018 0:00,2/18/2018 14:36
3,e64fb393e7b32834bb789ff8bb30750e,658677c97b385a9be170737859d3511b,5,4/21/2017 0:00,4/21/2017 22:02
4,f7c4243c7fe1938f181bec41a392bdeb,8e6bfb81e283fa7e4f11123a3fb894f1,5,3/1/2018 0:00,3/2/2018 10:26

In [13]:
orders = pd.read_csv("D:\AnalytixLabs\Case Studies\Machine Learning Assignments\Customer_360_Analytics_file_creation_assignment_2 - 1740904578730 - 1769931356551\ORDERS.csv")

In [14]:
orders.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,10/2/2017 10:56,10/2/2017 11:07,10/4/2017 19:55,10/10/2017 21:25,10/18/2017 0:00
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,7/24/2018 20:41,7/26/2018 3:24,7/26/2018 14:31,8/7/2018 15:27,8/13/2018 0:00
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,8/8/2018 8:38,8/8/2018 8:55,8/8/2018 13:50,8/17/2018 18:06,9/4/2018 0:00
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,11/18/2017 19:28,11/18/2017 19:45,11/22/2017 13:39,12/2/2017 0:28,12/15/2017 0:00
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2/13/2018 21:18,2/13/2018 22:20,2/14/2018 19:46,2/16/2018 18:17,2/26/2018 0:00

In [15]:
products = pd.read_csv("D:\AnalytixLabs\Case Studies\Machine Learning Assignments\Customer_360_Analytics_file_creation_assignment_2 - 1740904578730 - 1769931356551\PRODUCTS.csv")

In [17]:
products.head()

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
0,1e9e8ef04dbcff4541ed26657ea517e5,Perfumery,40.0,287.0,1.0,225.0,16.0,10.0,14.0
1,3aa071139cb16b67ca9e5dea641aaa2f,Art,44.0,276.0,1.0,1000.0,30.0,18.0,20.0
2,96bd76ec8810374ed1b65e291975717f,Sports_Leisure,46.0,250.0,1.0,154.0,18.0,9.0,15.0
3,cef67bcfe19066a932b7673e239eb23d,Baby,27.0,261.0,1.0,371.0,26.0,4.0,26.0
4,9dc1a7de274444849c219cff195d0b71,Housewares,37.0,402.0,4.0,625.0,20.0,17.0,13.0

In [18]:
sellers = pd.read_csv("D:\AnalytixLabs\Case Studies\Machine Learning Assignments\Customer_360_Analytics_file_creation_assignment_2 - 1740904578730 - 1769931356551\SELLERS.csv")

In [19]:
sellers.head()

,seller_id,seller_zip_code_prefix,seller_city,seller_state
0,3442f8959a84dea7ee197c632cb2df15,13023,Alwal,Andhra Pradesh
1,d1b65fc7debc3361ea86b5f14c68d2e2,13023,Alwal,Andhra Pradesh
2,ce3ad9de960102d0677a81f5d0bb7b2d,20031,Badepalle,Andhra Pradesh
3,c0f3eea2e14555b6faeea3dd58c1b1c3,4195,Akkarampalle,Andhra Pradesh
4,51a04a8a6bdcb23deccc82b0b80742cf,12914,Koratla,Andhra Pradesh

In [23]:
print(f'The dimensions of the customer dataframe is {customers.shape}')
print(f'The dimensions of the geo dataframe is {geo.shape}')
print(f'The dimensions of the items dataframe is {items.shape}')
print(f'The dimensions of the payments dataframe is {payments.shape}')
print(f'The dimensions of the ratings dataframe is {ratings.shape}')
print(f'The dimensions of the orders dataframe is {orders.shape}')
print(f'The dimensions of the products dataframe is {products.shape}')
print(f'The dimensions of the sellers dataframe is {sellers.shape}')

The dimensions of the customer dataframe is (99441, 4)
The dimensions of the geo dataframe is (19015, 5)
The dimensions of the items dataframe is (112650, 7)
The dimensions of the payments dataframe is (103886, 5)
The dimensions of the ratings dataframe is (100000, 5)
The dimensions of the orders dataframe is (99441, 8)
The dimensions of the products dataframe is (32951, 9)
The dimensions of the sellers dataframe is (3095, 4)